//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkelApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.HistorySkan = new HashSet<HistorySkan>();
            this.ImageProduct = new HashSet<ImageProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }

        [JsonIgnore]
        public virtual ICollection<HistorySkan> HistorySkan { get; set; }
        [JsonIgnore]
        public virtual ICollection<ImageProduct> ImageProduct { get; set; }
    }
}
